<?php

namespace Proxies\__CG__\GsbBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lignefraishorsforfait extends \GsbBundle\Entity\Lignefraishorsforfait implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idlignefraishorsforfait', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'libelle', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'datefrais', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'montant', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idetat', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idfiche');
        }

        return array('__isInitialized__', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idlignefraishorsforfait', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'libelle', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'datefrais', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'montant', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idetat', '' . "\0" . 'GsbBundle\\Entity\\Lignefraishorsforfait' . "\0" . 'idfiche');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lignefraishorsforfait $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdlignefraishorsforfait()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlignefraishorsforfait();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlignefraishorsforfait', array());

        return parent::getIdlignefraishorsforfait();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', array($libelle));

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', array());

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefrais($datefrais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefrais', array($datefrais));

        return parent::setDatefrais($datefrais);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefrais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefrais', array());

        return parent::getDatefrais();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', array($montant));

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', array());

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdetat(\GsbBundle\Entity\Etat $idetat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdetat', array($idetat));

        return parent::setIdetat($idetat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdetat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdetat', array());

        return parent::getIdetat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfiche(\GsbBundle\Entity\Fichefrais $idfiche = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfiche', array($idfiche));

        return parent::setIdfiche($idfiche);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfiche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfiche', array());

        return parent::getIdfiche();
    }

}
